- hosts: all
  tasks:
  - name: "shut down CentOS 6 and Debian 7 systems"
    shell: /usr/sbin/shutdown -r
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or
          (ansible_distribution == "Debian")
