- hosts: all
  tasks:
  - name: Find the Hostname with Architecture
    debug:
      msg: "My Hostname is {{ansible_hostname}} and distribution is {{ansible_distribution}} and major version is {{ansible_distribution_major_version}}"
  - name: Find Uptime for CentOS Machines
    command: uptime
    when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "16"
